/*-
 * #%L
 * Parsington: the SciJava mathematical expression parser.
 * %%
 * Copyright (C) 2015 - 2026 Parsington developers.
 * %%
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 * #L%
 */
package org.scijava.parsington;

import org.junit.jupiter.api.Test;

import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class OperatorsTest extends AbstractTest {

    @Test
    public void testStandardList() {
        // ensure the Operators static list matches a list generated by reflection on the Operators class
        List<Operator> fromStatic = Operators.standardList();
        List<Operator> fromReflection = standardList();
        Collections.sort(fromStatic);
        Collections.sort(fromReflection);

        assertEquals(fromStatic, fromReflection);
    }

    public List<Operator> standardList() {
        // Build the standard list from all available Operator constants.
        final ArrayList<Operator> ops = new ArrayList<>();
        for (final Field f : Operators.class.getFields()) {
            if (!isOperator(f)) continue;
            try {
                ops.add((Operator) f.get(null));
            } catch (final IllegalAccessException exc) {
                // This should never happen.
                throw new IllegalStateException(exc);
            }
        }
        return ops;
    }

    private boolean isOperator(final Field f) {
        final int mods = f.getModifiers();
        return Modifier.isStatic(mods) && Modifier.isFinal(mods) &&
                Operator.class.isAssignableFrom(f.getType());
    }

}
