package org.scijava.parsington;

import org.junit.jupiter.api.Test;

import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class OperatorsTest extends AbstractTest {

    @Test
    public void testStandardList() {
        // ensure the Operators static list matches a list generated by reflection on the Operators class
        List<Operator> fromStatic = Operators.standardList();
        List<Operator> fromReflection = standardList();
        Collections.sort(fromStatic);
        Collections.sort(fromReflection);

        assertEquals(fromStatic, fromReflection);
    }

    public List<Operator> standardList() {
        // Build the standard list from all available Operator constants.
        final ArrayList<Operator> ops = new ArrayList<>();
        for (final Field f : Operators.class.getFields()) {
            if (!isOperator(f)) continue;
            try {
                ops.add((Operator) f.get(null));
            } catch (final IllegalAccessException exc) {
                // This should never happen.
                throw new IllegalStateException(exc);
            }
        }
        return ops;
    }

    private boolean isOperator(final Field f) {
        final int mods = f.getModifiers();
        return Modifier.isStatic(mods) && Modifier.isFinal(mods) &&
                Operator.class.isAssignableFrom(f.getType());
    }

}